### PR TITLE
Update MUI versions from v4 to v5

### PR DESCRIPTION
**Pull request by rajivtitus**
### What this PR does (required):
- Update MUI version from v4 to v5

### Screenshots / Videos (front-end only):

Screen Shot 2021-11-18 at 6 40 58 PM

Screen Shot 2021-11-18 at 6 43 28 PM

### CODE REVIEW

**Review by bonnieli — COMMENTED** [review]
image
 

couple of errors on the frontend
- I think Autocomplete was moved from labs to v5 officially? but the components might look a bit different - maybe we can just remove it or update it

**Comment by rajivtitus** [comment]
@bonnieli Resolved MUI errors, thank you 😄

**Comment by rajivtitus** [comment]
> image
> 
> couple of errors on the frontend
> 
> * I think Autocomplete was moved from labs to v5 officially? but the components might look a bit different - maybe we can just remove it or update it

Yes, Autocomplete has moved from lab to mui core in V5, I've updated it accordingly!

**Review by bonnieli — APPROVED** [review]
super! other than those console log warnings, the upgrade worked beautifully!

**Comment by rajivtitus** [comment]
> super! other than those console log warnings, the upgrade worked beautifully!

Thank you 😄

**Pull request merged**
